import crafttweaker.api.recipe.Replacer;
import crafttweaker.api.item.IIngredient;
import crafttweaker.api.recipes.WrapperRecipe;

var ores as string[] = [
    "iron",
    "gold",
    "copper",
    "aluminum",
    "silver",
    "lead",
    "nickel",
    "tin",
    "zinc",

    "osmium",
    "uranium",

    "brass",
    "bronze",
    "cast_iron",
    "steel",
    "constantan",
    "electrum",
    "invar",
    "signalum",
    "lumium",
    "enderium",

    "cinnabar",
    "diamond",
    "emerald",
    "quartz",
    "coal",
    "charcoal",
    "sawdust",
    "wood",
    "ender",
    "apatite",
    "sulfur",
    "niter",
    "saltpeter",
    "lithium",
    "lapis",
    "coke",
    "obsidian",
    "fluorite"
];

var tags as IIngredient[] = [
    <tag:items:forge:ingots/iron>,
    <tag:items:forge:ingots/gold>,
    <tag:items:forge:ingots/copper>,
    <tag:items:forge:ingots/aluminum>,
    <tag:items:forge:ingots/silver>,
    <tag:items:forge:ingots/lead>,
    <tag:items:forge:ingots/nickel>,
    <tag:items:forge:ingots/tin>,
    <tag:items:forge:ingots/zinc>,
    <tag:items:forge:ingots/osmium>,
    <tag:items:forge:ingots/uranium>,
    <tag:items:forge:ingots/brass>,
    <tag:items:forge:ingots/bronze>,
    <tag:items:forge:ingots/cast_iron>,
    <tag:items:forge:ingots/steel>,
    <tag:items:forge:ingots/constantan>,
    <tag:items:forge:ingots/electrum>,
    <tag:items:forge:ingots/invar>,
    <tag:items:forge:ingots/signalum>,
    <tag:items:forge:ingots/lumium>,
    <tag:items:forge:ingots/enderium>,
    <tag:items:forge:ingots/netherite>,

    <tag:items:forge:dusts/iron>,
    <tag:items:forge:dusts/gold>,
    <tag:items:forge:dusts/copper>,
    <tag:items:forge:dusts/aluminum>,
    <tag:items:forge:dusts/silver>,
    <tag:items:forge:dusts/lead>,
    <tag:items:forge:dusts/nickel>,
    <tag:items:forge:dusts/tin>,
    <tag:items:forge:dusts/zinc>,
    <tag:items:forge:dusts/osmium>,
    <tag:items:forge:dusts/uranium>,
    <tag:items:forge:dusts/brass>,
    <tag:items:forge:dusts/bronze>,
    <tag:items:forge:dusts/cast_iron>,
    <tag:items:forge:dusts/steel>,
    <tag:items:forge:dusts/constantan>,
    <tag:items:forge:dusts/electrum>,
    <tag:items:forge:dusts/invar>,
    <tag:items:forge:dusts/signalum>,
    <tag:items:forge:dusts/lumium>,
    <tag:items:forge:dusts/enderium>,

    <tag:items:forge:dusts/cinnabar>,
    <tag:items:forge:dusts/diamond>,
    <tag:items:forge:dusts/emerald>,
    <tag:items:forge:dusts/quartz>,
    <tag:items:forge:dusts/coal>,
    <tag:items:forge:dusts/charcoal>,
    <tag:items:forge:dusts/wood>,
    <tag:items:forge:dusts/ender>,
    <tag:items:forge:dusts/apatite>,
    <tag:items:forge:dusts/sulfur>,
    <tag:items:forge:dusts/potassium_nitrate>,
    <tag:items:forge:dusts/niter>,
    <tag:items:forge:dusts/saltpeter>,
    
    <tag:items:forge:dusts/netherite>,
    <tag:items:forge:dusts/lithium>,
    <tag:items:forge:dusts/lapis>,
    <tag:items:forge:dusts/coal_coke>,
    <tag:items:forge:dusts/obsidian>,
    <tag:items:forge:dusts/fluorite>,

    <tag:items:forge:nuggets/iron>,
    <tag:items:forge:nuggets/gold>,
    <tag:items:forge:nuggets/copper>,
    <tag:items:forge:nuggets/aluminum>,
    <tag:items:forge:nuggets/silver>,
    <tag:items:forge:nuggets/lead>,
    <tag:items:forge:nuggets/nickel>,
    <tag:items:forge:nuggets/tin>,
    <tag:items:forge:nuggets/zinc>,
    <tag:items:forge:nuggets/osmium>,
    <tag:items:forge:nuggets/uranium>,
    <tag:items:forge:nuggets/brass>,
    <tag:items:forge:nuggets/bronze>,
    <tag:items:forge:nuggets/cast_iron>,
    <tag:items:forge:nuggets/steel>,
    <tag:items:forge:nuggets/constantan>,
    <tag:items:forge:nuggets/electrum>,
    <tag:items:forge:nuggets/invar>,
    <tag:items:forge:nuggets/signalum>,
    <tag:items:forge:nuggets/lumium>,
    <tag:items:forge:nuggets/enderium>,

    <tag:items:forge:gears/iron>,
    <tag:items:forge:gears/gold>,
    <tag:items:forge:gears/copper>,
    <tag:items:forge:gears/aluminum>,
    <tag:items:forge:gears/silver>,
    <tag:items:forge:gears/lead>,
    <tag:items:forge:gears/nickel>,
    <tag:items:forge:gears/tin>,
    <tag:items:forge:gears/zinc>,
    <tag:items:forge:gears/osmium>,
    <tag:items:forge:gears/uranium>,
    <tag:items:forge:gears/brass>,
    <tag:items:forge:gears/bronze>,
    <tag:items:forge:gears/cast_iron>,
    <tag:items:forge:gears/steel>,
    <tag:items:forge:gears/constantan>,
    <tag:items:forge:gears/electrum>,
    <tag:items:forge:gears/invar>,
    <tag:items:forge:gears/signalum>,
    <tag:items:forge:gears/lumium>,
    <tag:items:forge:gears/enderium>,
    <tag:items:forge:gears/netherite>,
    <tag:items:forge:gears/diamond>,
    <tag:items:forge:gears/emerald>,
    <tag:items:forge:gears/quartz>,
    <tag:items:forge:gears/lapis>,

    <tag:items:forge:plates/iron>,
    <tag:items:forge:plates/gold>,
    <tag:items:forge:plates/copper>,
    <tag:items:forge:plates/aluminum>,
    <tag:items:forge:plates/silver>,
    <tag:items:forge:plates/lead>,
    <tag:items:forge:plates/nickel>,
    <tag:items:forge:plates/tin>,
    <tag:items:forge:plates/zinc>,
    <tag:items:forge:plates/osmium>,
    <tag:items:forge:plates/uranium>,
    <tag:items:forge:plates/brass>,
    <tag:items:forge:plates/bronze>,
    <tag:items:forge:plates/cast_iron>,
    <tag:items:forge:plates/steel>,
    <tag:items:forge:plates/constantan>,
    <tag:items:forge:plates/electrum>,
    <tag:items:forge:plates/invar>,
    <tag:items:forge:plates/signalum>,
    <tag:items:forge:plates/lumium>,
    <tag:items:forge:plates/enderium>,
    <tag:items:forge:plates/netherite>,
    <tag:items:forge:plates/diamond>,
    <tag:items:forge:plates/emerald>,
    <tag:items:forge:plates/lapis>,

    <tag:items:forge:rods/iron>,
    <tag:items:forge:rods/gold>,
    <tag:items:forge:rods/copper>,
    <tag:items:forge:rods/aluminum>,
    <tag:items:forge:rods/silver>,
    <tag:items:forge:rods/lead>,
    <tag:items:forge:rods/nickel>,
    <tag:items:forge:rods/tin>,
    <tag:items:forge:rods/zinc>,
    <tag:items:forge:rods/osmium>,
    <tag:items:forge:rods/uranium>,
    <tag:items:forge:rods/brass>,
    <tag:items:forge:rods/bronze>,
    <tag:items:forge:rods/cast_iron>,
    <tag:items:forge:rods/steel>,
    <tag:items:forge:rods/constantan>,
    <tag:items:forge:rods/electrum>,
    <tag:items:forge:rods/invar>,
    <tag:items:forge:rods/signalum>,
    <tag:items:forge:rods/lumium>,
    <tag:items:forge:rods/enderium>,
    <tag:items:forge:rods/diamond>,
    <tag:items:forge:rods/emerald>,
    <tag:items:forge:rods/lapis>,

    <tag:items:forge:wires/copper>,

    <tag:items:forge:gems/diamond>,
    <tag:items:forge:gems/lapis>,
    <tag:items:forge:gems/emerald>,
    <tag:items:forge:gems/quartz>,
    <tag:items:forge:gems/cinnabar>,
    <tag:items:forge:gems/niter>,
    <tag:items:forge:gems/sulfur>,
    <tag:items:forge:gems/fluorite>,
];

var items as IIngredient[] = [
    <item:minecraft:iron_ingot>,
    <item:minecraft:gold_ingot>,
    <item:emendatusenigmatica:copper_ingot>,
    <item:emendatusenigmatica:aluminum_ingot>,
    <item:emendatusenigmatica:silver_ingot>,
    <item:emendatusenigmatica:lead_ingot>,
    <item:emendatusenigmatica:nickel_ingot>,
    <item:emendatusenigmatica:tin_ingot>,
    <item:emendatusenigmatica:zinc_ingot>,
    <item:emendatusenigmatica:osmium_ingot>,
    <item:emendatusenigmatica:uranium_ingot>,
    <item:emendatusenigmatica:brass_ingot>,
    <item:emendatusenigmatica:bronze_ingot>,
    <item:emendatusenigmatica:cast_iron_ingot>,
    <item:emendatusenigmatica:steel_ingot>,
    <item:emendatusenigmatica:constantan_ingot>,
    <item:emendatusenigmatica:electrum_ingot>,
    <item:emendatusenigmatica:invar_ingot>,
    <item:emendatusenigmatica:signalum_ingot>,
    <item:emendatusenigmatica:lumium_ingot>,
    <item:emendatusenigmatica:enderium_ingot>,
    <item:minecraft:netherite_ingot>,

    <item:emendatusenigmatica:iron_dust>,
    <item:emendatusenigmatica:gold_dust>,
    <item:emendatusenigmatica:copper_dust>,
    <item:emendatusenigmatica:aluminum_dust>,
    <item:emendatusenigmatica:silver_dust>,
    <item:emendatusenigmatica:lead_dust>,
    <item:emendatusenigmatica:nickel_dust>,
    <item:emendatusenigmatica:tin_dust>,
    <item:emendatusenigmatica:zinc_dust>,
    <item:emendatusenigmatica:osmium_dust>,
    <item:emendatusenigmatica:uranium_dust>,
    <item:emendatusenigmatica:brass_dust>,
    <item:emendatusenigmatica:bronze_dust>,
    <item:emendatusenigmatica:cast_iron_dust>,
    <item:emendatusenigmatica:steel_dust>,
    <item:emendatusenigmatica:constantan_dust>,
    <item:emendatusenigmatica:electrum_dust>,
    <item:emendatusenigmatica:invar_dust>,
    <item:emendatusenigmatica:signalum_dust>,
    <item:emendatusenigmatica:lumium_dust>,
    <item:emendatusenigmatica:enderium_dust>,

    <item:emendatusenigmatica:cinnabar_dust>,
    <item:emendatusenigmatica:diamond_dust>,
    <item:emendatusenigmatica:emerald_dust>,
    <item:emendatusenigmatica:quartz_dust>,
    <item:mekanism:dust_coal>,
    <item:mekanism:dust_charcoal>,
    <item:mekanism:sawdust>,
    <item:emendatusenigmatica:ender_dust>,
    <item:emendatusenigmatica:apatite_dust>,
    <item:emendatusenigmatica:sulfur_dust>,
    <item:emendatusenigmatica:potassium_nitrate_dust>,
    <item:emendatusenigmatica:potassium_nitrate_dust>,
    <item:emendatusenigmatica:potassium_nitrate_dust>,

    <item:thermal:netherite_dust>,
    <item:mekanism:dust_lithium>,
    <item:emendatusenigmatica:lapis_dust>,
    <item:emendatusenigmatica:coke_dust>,
    <item:emendatusenigmatica:obsidian_dust>,
    <item:emendatusenigmatica:fluorite_dust>,

    <item:minecraft:iron_nugget>,
    <item:minecraft:gold_nugget>,
    <item:emendatusenigmatica:copper_nugget>,
    <item:emendatusenigmatica:aluminum_nugget>,
    <item:emendatusenigmatica:silver_nugget>,
    <item:emendatusenigmatica:lead_nugget>,
    <item:emendatusenigmatica:nickel_nugget>,
    <item:emendatusenigmatica:tin_nugget>,
    <item:emendatusenigmatica:zinc_nugget>,
    <item:emendatusenigmatica:osmium_nugget>,
    <item:emendatusenigmatica:uranium_nugget>,
    <item:emendatusenigmatica:brass_nugget>,
    <item:emendatusenigmatica:bronze_nugget>,
    <item:emendatusenigmatica:cast_iron_nugget>,
    <item:emendatusenigmatica:steel_nugget>,
    <item:emendatusenigmatica:constantan_nugget>,
    <item:emendatusenigmatica:electrum_nugget>,
    <item:emendatusenigmatica:invar_nugget>,
    <item:emendatusenigmatica:signalum_nugget>,
    <item:emendatusenigmatica:lumium_nugget>,
    <item:emendatusenigmatica:enderium_nugget>,

    <item:emendatusenigmatica:iron_gear>,
    <item:emendatusenigmatica:gold_gear>,
    <item:emendatusenigmatica:copper_gear>,
    <item:emendatusenigmatica:aluminum_gear>,
    <item:emendatusenigmatica:silver_gear>,
    <item:emendatusenigmatica:lead_gear>,
    <item:emendatusenigmatica:nickel_gear>,
    <item:emendatusenigmatica:tin_gear>,
    <item:emendatusenigmatica:zinc_gear>,
    <item:emendatusenigmatica:osmium_gear>,
    <item:emendatusenigmatica:uranium_gear>,
    <item:emendatusenigmatica:brass_gear>,
    <item:emendatusenigmatica:bronze_gear>,
    <item:emendatusenigmatica:cast_iron_gear>,
    <item:emendatusenigmatica:steel_gear>,
    <item:emendatusenigmatica:constantan_gear>,
    <item:emendatusenigmatica:electrum_gear>,
    <item:emendatusenigmatica:invar_gear>,
    <item:emendatusenigmatica:signalum_gear>,
    <item:emendatusenigmatica:lumium_gear>,
    <item:emendatusenigmatica:enderium_gear>,
    <item:thermal:netherite_gear>,
    <item:emendatusenigmatica:diamond_gear>,
    <item:emendatusenigmatica:emerald_gear>,
    <item:emendatusenigmatica:quartz_gear>,
    <item:emendatusenigmatica:lapis_gear>,

    <item:emendatusenigmatica:iron_plate>,
    <item:emendatusenigmatica:gold_plate>,
    <item:emendatusenigmatica:copper_plate>,
    <item:emendatusenigmatica:aluminum_plate>,
    <item:emendatusenigmatica:silver_plate>,
    <item:emendatusenigmatica:lead_plate>,
    <item:emendatusenigmatica:nickel_plate>,
    <item:emendatusenigmatica:tin_plate>,
    <item:emendatusenigmatica:zinc_plate>,
    <item:emendatusenigmatica:osmium_plate>,
    <item:emendatusenigmatica:uranium_plate>,
    <item:emendatusenigmatica:brass_plate>,
    <item:emendatusenigmatica:bronze_plate>,
    <item:emendatusenigmatica:cast_iron_plate>,
    <item:emendatusenigmatica:steel_plate>,
    <item:emendatusenigmatica:constantan_plate>,
    <item:emendatusenigmatica:electrum_plate>,
    <item:emendatusenigmatica:invar_plate>,
    <item:emendatusenigmatica:signalum_plate>,
    <item:emendatusenigmatica:lumium_plate>,
    <item:emendatusenigmatica:enderium_plate>,
    <item:thermal:netherite_plate>,
    <item:emendatusenigmatica:diamond_plate>,
    <item:emendatusenigmatica:emerald_plate>,
    <item:emendatusenigmatica:lapis_plate>,

    <item:emendatusenigmatica:iron_rod>,
    <item:emendatusenigmatica:gold_rod>,
    <item:emendatusenigmatica:copper_rod>,
    <item:emendatusenigmatica:aluminum_rod>,
    <item:emendatusenigmatica:silver_rod>,
    <item:emendatusenigmatica:lead_rod>,
    <item:emendatusenigmatica:nickel_rod>,
    <item:emendatusenigmatica:tin_rod>,
    <item:emendatusenigmatica:zinc_rod>,
    <item:emendatusenigmatica:osmium_rod>,
    <item:emendatusenigmatica:uranium_rod>,
    <item:emendatusenigmatica:brass_rod>,
    <item:emendatusenigmatica:bronze_rod>,
    <item:emendatusenigmatica:cast_iron_rod>,
    <item:emendatusenigmatica:steel_rod>,
    <item:emendatusenigmatica:constantan_rod>,
    <item:emendatusenigmatica:electrum_rod>,
    <item:emendatusenigmatica:invar_rod>,
    <item:emendatusenigmatica:signalum_rod>,
    <item:emendatusenigmatica:lumium_rod>,
    <item:emendatusenigmatica:enderium_rod>,
    <item:emendatusenigmatica:diamond_rod>,
    <item:emendatusenigmatica:emerald_rod>,
    <item:emendatusenigmatica:lapis_rod>,

    <item:immersiveengineering:wire_copper>,

    <item:minecraft:diamond>,
    <item:minecraft:lapis_lazuli>,
    <item:minecraft:emerald>,
    <item:minecraft:quartz>,
    <item:thermal:cinnabar>,
    <item:thermal:niter>,
    <item:thermal:sulfur>,
    <item:emendatusenigmatica:fluorite_gem>,
];

/* var replaceTagToItem as IIngredient[][] = [
    [<tag:items:forge:ingots/iron>, <item:minecraft:iron_ingot>],
    [<tag:items:forge:ingots/gold>, <item:minecraft:gold_ingot>],
    [<tag:items:forge:ingots/copper>, <item:emendatusenigmatica:copper_ingot>],
    [<tag:items:forge:ingots/aluminum>, <item:emendatusenigmatica:aluminum_ingot>],
    [<tag:items:forge:ingots/silver>, <item:emendatusenigmatica:silver_ingot>],
    [<tag:items:forge:ingots/lead>, <item:emendatusenigmatica:lead_ingot>],
    [<tag:items:forge:ingots/nickel>, <item:emendatusenigmatica:nickel_ingot>],
    [<tag:items:forge:ingots/tin>, <item:emendatusenigmatica:tin_ingot>],
    [<tag:items:forge:ingots/zinc>, <item:emendatusenigmatica:zinc_ingot>],
    [<tag:items:forge:ingots/osmium>, <item:emendatusenigmatica:osmium_ingot>],
    [<tag:items:forge:ingots/uranium>, <item:emendatusenigmatica:uranium_ingot>],
    [<tag:items:forge:ingots/brass>, <item:emendatusenigmatica:brass_ingot>],
    [<tag:items:forge:ingots/bronze>, <item:emendatusenigmatica:bronze_ingot>],
    [<tag:items:forge:ingots/cast_iron>, <item:emendatusenigmatica:cast_iron_ingot>],
    [<tag:items:forge:ingots/steel>, <item:emendatusenigmatica:steel_ingot>],
    [<tag:items:forge:ingots/constantan>, <item:emendatusenigmatica:constantan_ingot>],
    [<tag:items:forge:ingots/electrum>, <item:emendatusenigmatica:electrum_ingot>],
    [<tag:items:forge:ingots/invar>, <item:emendatusenigmatica:invar_ingot>],
    [<tag:items:forge:ingots/signalum>, <item:emendatusenigmatica:signalum_ingot>],
    [<tag:items:forge:ingots/lumium>, <item:emendatusenigmatica:lumium_ingot>],
    [<tag:items:forge:ingots/enderium>, <item:emendatusenigmatica:enderium_ingot>],
    [<tag:items:forge:ingots/netherite>, <item:minecraft:netherite_ingot>],

    [<tag:items:forge:dusts/iron>, <item:emendatusenigmatica:iron_dust>],
    [<tag:items:forge:dusts/gold>, <item:emendatusenigmatica:gold_dust>],
    [<tag:items:forge:dusts/copper>, <item:emendatusenigmatica:copper_dust>],
    [<tag:items:forge:dusts/aluminum>, <item:emendatusenigmatica:aluminum_dust>],
    [<tag:items:forge:dusts/silver>, <item:emendatusenigmatica:silver_dust>],
    [<tag:items:forge:dusts/lead>, <item:emendatusenigmatica:lead_dust>],
    [<tag:items:forge:dusts/nickel>, <item:emendatusenigmatica:nickel_dust>],
    [<tag:items:forge:dusts/tin>, <item:emendatusenigmatica:tin_dust>],
    [<tag:items:forge:dusts/zinc>, <item:emendatusenigmatica:zinc_dust>],
    [<tag:items:forge:dusts/osmium>, <item:emendatusenigmatica:osmium_dust>],
    [<tag:items:forge:dusts/uranium>, <item:emendatusenigmatica:uranium_dust>],
    [<tag:items:forge:dusts/brass>, <item:emendatusenigmatica:brass_dust>],
    [<tag:items:forge:dusts/bronze>, <item:emendatusenigmatica:bronze_dust>],
    [<tag:items:forge:dusts/cast_iron>, <item:emendatusenigmatica:cast_iron_dust>],
    [<tag:items:forge:dusts/steel>, <item:emendatusenigmatica:steel_dust>],
    [<tag:items:forge:dusts/constantan>, <item:emendatusenigmatica:constantan_dust>],
    [<tag:items:forge:dusts/electrum>, <item:emendatusenigmatica:electrum_dust>],
    [<tag:items:forge:dusts/invar>, <item:emendatusenigmatica:invar_dust>],
    [<tag:items:forge:dusts/signalum>, <item:emendatusenigmatica:signalum_dust>],
    [<tag:items:forge:dusts/lumium>, <item:emendatusenigmatica:lumium_dust>],
    [<tag:items:forge:dusts/enderium>, <item:emendatusenigmatica:enderium_dust>],

    [<tag:items:forge:dusts/cinnabar>, <item:emendatusenigmatica:cinnabar_dust>],
    [<tag:items:forge:dusts/diamond>, <item:emendatusenigmatica:diamond_dust>],
    [<tag:items:forge:dusts/emerald>, <item:emendatusenigmatica:emerald_dust>],
    [<tag:items:forge:dusts/quartz>, <item:emendatusenigmatica:quartz_dust>],
    [<tag:items:forge:dusts/coal>, <item:emendatusenigmatica:coal_dust>],
    [<tag:items:forge:dusts/charcoal>, <item:emendatusenigmatica:charcoal_dust>],
    [<tag:items:forge:dusts/wood>, <item:emendatusenigmatica:wood_dust>],
    [<tag:items:forge:dusts/ender>, <item:emendatusenigmatica:ender_dust>],
    [<tag:items:forge:dusts/apatite>, <item:emendatusenigmatica:apatite_dust>],
    [<tag:items:forge:dusts/sulfur>, <item:emendatusenigmatica:sulfur_dust>],
    [<tag:items:forge:dusts/potassium_nitrate>, <item:emendatusenigmatica:potassium_nitrate_dust>],
    [<tag:items:forge:dusts/niter>, <item:emendatusenigmatica:potassium_nitrate_dust>],
    [<tag:items:forge:dusts/saltpeter>, <item:emendatusenigmatica:potassium_nitrate_dust>],

    [<tag:items:forge:dusts/netherite>, <item:thermal:netherite_dust>],
    [<tag:items:forge:dusts/lithium>, <item:emendatusenigmatica:lithium_dust>],
    [<tag:items:forge:dusts/lapis>, <item:emendatusenigmatica:lapis_dust>],
    [<tag:items:forge:dusts/coal_coke>, <item:emendatusenigmatica:coke_dust>],
    [<tag:items:forge:dusts/obsidian>, <item:emendatusenigmatica:obsidian_dust>],
    [<tag:items:forge:dusts/fluorite>, <item:emendatusenigmatica:fluorite_dust>],

    [<tag:items:forge:nuggets/iron>, <item:minecraft:iron_nugget>],
    [<tag:items:forge:nuggets/gold>, <item:minecraft:gold_nugget>],
    [<tag:items:forge:nuggets/copper>, <item:emendatusenigmatica:copper_nugget>],
    [<tag:items:forge:nuggets/aluminum>, <item:emendatusenigmatica:aluminum_nugget>],
    [<tag:items:forge:nuggets/silver>, <item:emendatusenigmatica:silver_nugget>],
    [<tag:items:forge:nuggets/lead>, <item:emendatusenigmatica:lead_nugget>],
    [<tag:items:forge:nuggets/nickel>, <item:emendatusenigmatica:nickel_nugget>],
    [<tag:items:forge:nuggets/tin>, <item:emendatusenigmatica:tin_nugget>],
    [<tag:items:forge:nuggets/zinc>, <item:emendatusenigmatica:zinc_nugget>],
    [<tag:items:forge:nuggets/osmium>, <item:emendatusenigmatica:osmium_nugget>],
    [<tag:items:forge:nuggets/uranium>, <item:emendatusenigmatica:uranium_nugget>],
    [<tag:items:forge:nuggets/brass>, <item:emendatusenigmatica:brass_nugget>],
    [<tag:items:forge:nuggets/bronze>, <item:emendatusenigmatica:bronze_nugget>],
    [<tag:items:forge:nuggets/cast_iron>, <item:emendatusenigmatica:cast_iron_nugget>],
    [<tag:items:forge:nuggets/steel>, <item:emendatusenigmatica:steel_nugget>],
    [<tag:items:forge:nuggets/constantan>, <item:emendatusenigmatica:constantan_nugget>],
    [<tag:items:forge:nuggets/electrum>, <item:emendatusenigmatica:electrum_nugget>],
    [<tag:items:forge:nuggets/invar>, <item:emendatusenigmatica:invar_nugget>],
    [<tag:items:forge:nuggets/signalum>, <item:emendatusenigmatica:signalum_nugget>],
    [<tag:items:forge:nuggets/lumium>, <item:emendatusenigmatica:lumium_nugget>],
    [<tag:items:forge:nuggets/enderium>, <item:emendatusenigmatica:enderium_nugget>],

    [<tag:items:forge:gears/iron>, <item:emendatusenigmatica:iron_gear>],
    [<tag:items:forge:gears/gold>, <item:emendatusenigmatica:gold_gear>],
    [<tag:items:forge:gears/copper>, <item:emendatusenigmatica:copper_gear>],
    [<tag:items:forge:gears/aluminum>, <item:emendatusenigmatica:aluminum_gear>],
    [<tag:items:forge:gears/silver>, <item:emendatusenigmatica:silver_gear>],
    [<tag:items:forge:gears/lead>, <item:emendatusenigmatica:lead_gear>],
    [<tag:items:forge:gears/nickel>, <item:emendatusenigmatica:nickel_gear>],
    [<tag:items:forge:gears/tin>, <item:emendatusenigmatica:tin_gear>],
    [<tag:items:forge:gears/zinc>, <item:emendatusenigmatica:zinc_gear>],
    [<tag:items:forge:gears/osmium>, <item:emendatusenigmatica:osmium_gear>],
    [<tag:items:forge:gears/uranium>, <item:emendatusenigmatica:uranium_gear>],
    [<tag:items:forge:gears/brass>, <item:emendatusenigmatica:brass_gear>],
    [<tag:items:forge:gears/bronze>, <item:emendatusenigmatica:bronze_gear>],
    [<tag:items:forge:gears/cast_iron>, <item:emendatusenigmatica:cast_iron_gear>],
    [<tag:items:forge:gears/steel>, <item:emendatusenigmatica:steel_gear>],
    [<tag:items:forge:gears/constantan>, <item:emendatusenigmatica:constantan_gear>],
    [<tag:items:forge:gears/electrum>, <item:emendatusenigmatica:electrum_gear>],
    [<tag:items:forge:gears/invar>, <item:emendatusenigmatica:invar_gear>],
    [<tag:items:forge:gears/signalum>, <item:emendatusenigmatica:signalum_gear>],
    [<tag:items:forge:gears/lumium>, <item:emendatusenigmatica:lumium_gear>],
    [<tag:items:forge:gears/enderium>, <item:emendatusenigmatica:enderium_gear>],
    [<tag:items:forge:gears/netherite>, <item:thermal:netherite_gear>],
    [<tag:items:forge:gears/diamond>, <item:emendatusenigmatica:diamond_gear>],
    [<tag:items:forge:gears/emerald>, <item:emendatusenigmatica:emerald_gear>],
    [<tag:items:forge:gears/quartz>, <item:emendatusenigmatica:quartz_gear>],
    [<tag:items:forge:gears/lapis>, <item:emendatusenigmatica:lapis_gear>],

    [<tag:items:forge:plates/iron>, <item:emendatusenigmatica:iron_plate>],
    [<tag:items:forge:plates/gold>, <item:emendatusenigmatica:gold_plate>],
    [<tag:items:forge:plates/copper>, <item:emendatusenigmatica:copper_plate>],
    [<tag:items:forge:plates/aluminum>, <item:emendatusenigmatica:aluminum_plate>],
    [<tag:items:forge:plates/silver>, <item:emendatusenigmatica:silver_plate>],
    [<tag:items:forge:plates/lead>, <item:emendatusenigmatica:lead_plate>],
    [<tag:items:forge:plates/nickel>, <item:emendatusenigmatica:nickel_plate>],
    [<tag:items:forge:plates/tin>, <item:emendatusenigmatica:tin_plate>],
    [<tag:items:forge:plates/zinc>, <item:emendatusenigmatica:zinc_plate>],
    [<tag:items:forge:plates/osmium>, <item:emendatusenigmatica:osmium_plate>],
    [<tag:items:forge:plates/uranium>, <item:emendatusenigmatica:uranium_plate>],
    [<tag:items:forge:plates/brass>, <item:emendatusenigmatica:brass_plate>],
    [<tag:items:forge:plates/bronze>, <item:emendatusenigmatica:bronze_plate>],
    [<tag:items:forge:plates/cast_iron>, <item:emendatusenigmatica:cast_iron_plate>],
    [<tag:items:forge:plates/steel>, <item:emendatusenigmatica:steel_plate>],
    [<tag:items:forge:plates/constantan>, <item:emendatusenigmatica:constantan_plate>],
    [<tag:items:forge:plates/electrum>, <item:emendatusenigmatica:electrum_plate>],
    [<tag:items:forge:plates/invar>, <item:emendatusenigmatica:invar_plate>],
    [<tag:items:forge:plates/signalum>, <item:emendatusenigmatica:signalum_plate>],
    [<tag:items:forge:plates/lumium>, <item:emendatusenigmatica:lumium_plate>],
    [<tag:items:forge:plates/enderium>, <item:emendatusenigmatica:enderium_plate>],
    [<tag:items:forge:plates/netherite>, <item:thermal:netherite_plate>],
    [<tag:items:forge:plates/diamond>, <item:emendatusenigmatica:diamond_plate>],
    [<tag:items:forge:plates/emerald>, <item:emendatusenigmatica:emerald_plate>],
    [<tag:items:forge:plates/lapis>, <item:emendatusenigmatica:lapis_plate>],

    [<tag:items:forge:rods/iron>, <item:emendatusenigmatica:iron_rod>],
    [<tag:items:forge:rods/gold>, <item:emendatusenigmatica:gold_rod>],
    [<tag:items:forge:rods/copper>, <item:emendatusenigmatica:copper_rod>],
    [<tag:items:forge:rods/aluminum>, <item:emendatusenigmatica:aluminum_rod>],
    [<tag:items:forge:rods/silver>, <item:emendatusenigmatica:silver_rod>],
    [<tag:items:forge:rods/lead>, <item:emendatusenigmatica:lead_rod>],
    [<tag:items:forge:rods/nickel>, <item:emendatusenigmatica:nickel_rod>],
    [<tag:items:forge:rods/tin>, <item:emendatusenigmatica:tin_rod>],
    [<tag:items:forge:rods/zinc>, <item:emendatusenigmatica:zinc_rod>],
    [<tag:items:forge:rods/osmium>, <item:emendatusenigmatica:osmium_rod>],
    [<tag:items:forge:rods/uranium>, <item:emendatusenigmatica:uranium_rod>],
    [<tag:items:forge:rods/brass>, <item:emendatusenigmatica:brass_rod>],
    [<tag:items:forge:rods/bronze>, <item:emendatusenigmatica:bronze_rod>],
    [<tag:items:forge:rods/cast_iron>, <item:emendatusenigmatica:cast_iron_rod>],
    [<tag:items:forge:rods/steel>, <item:emendatusenigmatica:steel_rod>],
    [<tag:items:forge:rods/constantan>, <item:emendatusenigmatica:constantan_rod>],
    [<tag:items:forge:rods/electrum>, <item:emendatusenigmatica:electrum_rod>],
    [<tag:items:forge:rods/invar>, <item:emendatusenigmatica:invar_rod>],
    [<tag:items:forge:rods/signalum>, <item:emendatusenigmatica:signalum_rod>],
    [<tag:items:forge:rods/lumium>, <item:emendatusenigmatica:lumium_rod>],
    [<tag:items:forge:rods/enderium>, <item:emendatusenigmatica:enderium_rod>],
    [<tag:items:forge:rods/diamond>, <item:emendatusenigmatica:diamond_rod>],
    [<tag:items:forge:rods/emerald>, <item:emendatusenigmatica:emerald_rod>],
    [<tag:items:forge:rods/lapis>, <item:emendatusenigmatica:lapis_rod>],
]; */

for i, tag in tags {
    Replacer.forEverything().replace(tags[i], items[i]).suppressWarnings().execute();
}

/* for replacing in replaceTagToItem {
    Replacer.forEverything().replace(replacing[0], replacing[1]).suppressWarnings().execute();
} */